## Imports

In [1]:
import pandas as pd
import ast
from google.colab import userdata, drive
from tqdm import tqdm
import typing_extensions as typing
import google.generativeai as genai
import json
import time
import os
import csv
from datetime import datetime, timedelta
from abc import ABC, abstractmethod
from openai import OpenAI

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [2]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Extract Data

In [3]:
# 1. Load the data and convert strings back to real Python lists
clinical_trials_df = pd.read_csv("/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/processed_studies.csv")
# clinical_trials_df['inclusion_criteria'] = clinical_trials_df['inclusion_criteria'].apply(ast.literal_eval)

In [4]:
mimic_patients_df = pd.read_parquet("/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/df_diag_final_elegibility.parquet")
print(mimic_patients_df.columns.tolist())

['subject_id', 'hadm_id', 'HPI', 'physical_exam', 'chief_complaint', 'icd_diag_principal', 'name_diag_principal', 'list_procedures', '% Hemoglobin A1c', '25-OH Vitamin D', 'ADP', 'ANCA Titer', 'ARCH-1', 'Absolute Basophil Count', 'Absolute CD3 Count', 'Absolute CD4 Count', 'Absolute CD8 Count', 'Absolute Eosinophil Count', 'Absolute Lymphocyte Count', 'Absolute Monocyte Count', 'Absolute Neutrophil Count', 'Acanthocytes', 'Acetaminophen', 'Acetone', 'Alanine Aminotransferase (ALT)', 'Albumin', 'Alkaline Phosphatase', 'Alpha-Fetoprotein', 'Alveolar-arterial Gradient', 'Ammonia', 'Amylase', 'Anion Gap', 'Anisocytosis', 'Anti-Mitochondrial Antibody', 'Anti-Neutrophil Cytoplasmic Antibody', 'Anti-Nuclear Antibody', 'Anti-Nuclear Antibody, Titer', 'Anti-Smooth Muscle Antibody', 'Anti-Thyroglobulin Antibodies', 'Anticardiolipin Antibody IgG', 'Anticardiolipin Antibody IgM', 'Antithrombin', 'Arachadonic Acid', 'Asparate Aminotransferase (AST)', 'Assist/Control', 'Atypical Lymphocytes', 'Bands', 'Barbiturate Screen', 'Base Excess', 'Basophilic Stippling', 'Basophils', 'Benzodiazepine Screen', 'Beta-2 Microglobulin', 'Bicarbonate', 'Bilirubin, Direct', 'Bilirubin, Indirect', 'Bilirubin, Total', 'Bite Cells', 'Blasts', 'Blood Parasite Smear', 'Blue Top Hold', 'Blue Top Hold Frozen', 'C-Reactive Protein', 'C3', 'C4', 'CA-125', 'CD10', 'CD117', 'CD13', 'CD14', 'CD15', 'CD16/56 Absolute Count', 'CD16/56%', 'CD19', 'CD19 %', 'CD19 Absolute Count', 'CD2', 'CD20', 'CD20 %', 'CD20 Absolute Count', 'CD23', 'CD3 %', 'CD3 Absolute Count', 'CD3 Cells, Percent', 'CD33', 'CD34', 'CD4 Cells, Percent', 'CD4/CD8 Ratio', 'CD45', 'CD5', 'CD5 %', 'CD5 Absolute Count', 'CD56', 'CD64', 'CD7', 'CD8 Cells, Percent', 'CK-MB Index', 'Calcium, Total', 'Calculated Bicarbonate, Whole Blood', 'Calculated TBG', 'Calculated Thyroxine (T4) Index', 'Calculated Total CO2', 'Cancer Antigen 27.29', 'Carboxyhemoglobin', 'Carcinoembyronic Antigen (CEA)', 'Centromere', 'Chloride', 'Chloride, Whole Blood', 'Cholesterol Ratio (Total/HDL)', 'Cholesterol, HDL', 'Cholesterol, LDL, Calculated', 'Cholesterol, LDL, Measured', 'Cholesterol, Total', 'Collagen', 'Cortisol', 'Creatine Kinase (CK)', 'Creatine Kinase, MB Isoenzyme', 'Creatinine', 'Creatinine, Whole Blood', 'Cryoglobulin', 'Cyclosporin', 'Cytomegalovirus Viral Load', 'D-Dimer', 'DHEA-Sulfate', 'Digoxin', 'Double Stranded DNA', 'EDTA Hold', 'EE1', 'EE2', 'EE3', 'EE5', 'EE6', 'EE7', 'Echinocytes', 'Elliptocytes', 'Envelope Cells', 'Eosinophil Count', 'Eosinophils', 'Epinepherine', 'Estimated GFR (MDRD equation)', 'Ethanol', 'FMC-7', 'Factor II', 'Factor V', 'Factor VII', 'Factor VIII', 'Factor X', 'Ferritin', 'Fibrin Degradation Products', 'Fibrinogen, Functional', 'Folate', 'Fragmented Cells', 'Free Calcium', 'Free Kappa', 'Free Kappa/Free Lambda Ratio', 'Free Lambda', 'G6PD, Qualitative', 'Gamma Glutamyltransferase', 'Gentamicin', 'Globulin', 'Glucose', 'Granulocyte Count', 'Gray Top Hold (plasma)', 'Green Top Hold (plasma)', 'H', 'H/O Smear', 'HIT-Ab Interpreted Result', 'HIT-Ab Numerical Result', 'HIV 1 Ab Confirmation', 'HIV 1 Viral Load', 'HIV 2 Ab Confirmation', 'HIV Screen', 'HLA-DR', 'HPE1', 'HPE2', 'HPE3', 'HPE4', 'HPE5', 'HPE6', 'HPE7', 'HPE8', 'Haptoglobin', 'Hematocrit', 'Hematocrit, Calculated', 'Hemoglobin', 'Hemoglobin A2', 'Hemoglobin C', 'Hemoglobin F', 'Hemogloblin A', 'Hemogloblin S', 'Heparin', 'Heparin, LMW', 'Hepatitis A Virus Antibody', 'Hepatitis A Virus IgM Antibody', 'Hepatitis B Core Antibody, IgM', 'Hepatitis B Surface Antibody', 'Hepatitis B Surface Antigen', 'Hepatitis B Viral Load', 'Hepatitis B Virus Core Antibody', 'Hepatitis C Viral Load', 'Hepatitis C Virus Antibody', 'Homocysteine', 'Howell-Jolly Bodies', 'Human Chorionic Gonadotropin', 'Hypochromia', 'I', 'INR(PT)', 'Immature Granulocytes', 'Immunofixation', 'Immunoglobulin A', 'Immunoglobulin G', 'Immunoglobulin M', 'Immunophenotyping', 'Inhibitor Screen', 'Inpatient Hematology/Oncology Smear', 'Intubated', 'Iron', 'Iron Binding Capacity, Total', 'Kappa', 'L', 'LUC', 'Lactate', 'Lactate Dehydrogenase (LD)', 'Lambda', 'Large Platelets', 'Light Green Top Hold', 'Lipase', 'Lithium', 'Lupus Anticoagulant', 'Lymphocytes', 'Lymphocytes, Percent', 'MCH', 'MCHC', 'MCV', 'MacroOvalocytes', 'Macrocytes', 'Magnesium', 'Metamyelocytes', 'Methemoglobin', 'Methotrexate', 'Microcytes', 'Monocytes', 'Myelocytes', 'NTproBNP', 'Neutrophils', 'Nucleated Red Cells', 'O2 Flow', 'Osmolality, Measured', 'Other Cells', 'Ovalocytes', 'Oxygen', 'Oxygen Saturation', 'PEEP', 'PT', 'PTT', 'Pappenheimer Bodies', 'Parathyroid Hormone', 'Pencil Cells', 'Phenobarbital', 'Phenytoin', 'Phenytoin, Free', 'Phenytoin, Percent Free', 'Phosphate', 'Plasma Cells', 'Platelet Clumps', 'Platelet Count', 'Platelet Smear', 'Poikilocytosis', 'Polychromasia', 'Potassium', 'Potassium, Whole Blood', 'Problem Specimen', 'Promyelocytes', 'Prostate Specific Antigen', 'Protein C, Antigen', 'Protein C, Functional', 'Protein Electrophoresis', 'Protein S, Antigen', 'Protein S, Functional', 'Protein, Total', 'Quantitative G6PD', 'RBC Morphology', 'RDW', 'RDW-SD', 'RFXLDLM', 'Rapamycin', 'Red Blood Cells', 'Red Top Hold', 'Required O2', 'Reticulocyte Count, Absolute', 'Reticulocyte Count, Automated', 'Reticulocyte Count, Manual', 'Rheumatoid Factor', 'STX1', 'STX2', 'STX3', 'STX4', 'STX5', 'STX6', 'Salicylate', 'Schistocytes', 'Sedimentation Rate', 'Serum Viscosity', 'Sickle Cells', 'Sodium', 'Sodium, Whole Blood', 'Specimen Type', 'Spherocytes', 'Target Cells', 'Teardrop Cells', 'Temperature', 'Thrombin', 'Thyroglobulin', 'Thyroid Peroxidase Antibodies', 'Thyroid Stimulating Hormone', 'Thyroxine (T4)', 'Thyroxine (T4), Free', 'Tidal Volume', 'Tissue Transglutaminase Ab, IgA', 'Tobramycin', 'Transferrin', 'Tricyclic Antidepressant Screen', 'Triglycerides', 'Triiodothyronine (T3)', 'Troponin T', 'Uptake Ratio', 'Urea Nitrogen', 'Uric Acid', 'Valproic Acid', 'Vancomycin', 'Ventilation Rate', 'Ventilator', 'Vitamin B12', 'Voided Specimen', 'Von Willebrand Factor Activity', 'Von Willebrand Factor Antigen', 'WBC Count', 'White Blood Cells', 'Young Cells', 'eAG', 'pCO2', 'pH', 'pO2', 'tacroFK', '% Hemoglobin A1c_FLAG', '25-OH Vitamin D_FLAG', 'ADP_FLAG', 'ANCA Titer_FLAG', 'ARCH-1_FLAG', 'Absolute Basophil Count_FLAG', 'Absolute CD3 Count_FLAG', 'Absolute CD4 Count_FLAG', 'Absolute CD8 Count_FLAG', 'Absolute Eosinophil Count_FLAG', 'Absolute Lymphocyte Count_FLAG', 'Absolute Monocyte Count_FLAG', 'Absolute Neutrophil Count_FLAG', 'Acanthocytes_FLAG', 'Acetaminophen_FLAG', 'Acetone_FLAG', 'Alanine Aminotransferase (ALT)_FLAG', 'Albumin_FLAG', 'Alkaline Phosphatase_FLAG', 'Alpha-Fetoprotein_FLAG', 'Alveolar-arterial Gradient_FLAG', 'Ammonia_FLAG', 'Amylase_FLAG', 'Anion Gap_FLAG', 'Anisocytosis_FLAG', 'Anti-Mitochondrial Antibody_FLAG', 'Anti-Neutrophil Cytoplasmic Antibody_FLAG', 'Anti-Nuclear Antibody_FLAG', 'Anti-Nuclear Antibody, Titer_FLAG', 'Anti-Smooth Muscle Antibody_FLAG', 'Anti-Thyroglobulin Antibodies_FLAG', 'Anticardiolipin Antibody IgG_FLAG', 'Anticardiolipin Antibody IgM_FLAG', 'Antithrombin_FLAG', 'Arachadonic Acid_FLAG', 'Asparate Aminotransferase (AST)_FLAG', 'Assist/Control_FLAG', 'Atypical Lymphocytes_FLAG', 'Bands_FLAG', 'Barbiturate Screen_FLAG', 'Base Excess_FLAG', 'Basophilic Stippling_FLAG', 'Basophils_FLAG', 'Benzodiazepine Screen_FLAG', 'Beta-2 Microglobulin_FLAG', 'Bicarbonate_FLAG', 'Bilirubin, Direct_FLAG', 'Bilirubin, Indirect_FLAG', 'Bilirubin, Total_FLAG', 'Bite Cells_FLAG', 'Blasts_FLAG', 'Blood Parasite Smear_FLAG', 'Blue Top Hold_FLAG', 'Blue Top Hold Frozen_FLAG', 'C-Reactive Protein_FLAG', 'C3_FLAG', 'C4_FLAG', 'CA-125_FLAG', 'CD10_FLAG', 'CD117_FLAG', 'CD13_FLAG', 'CD14_FLAG', 'CD15_FLAG', 'CD16/56 Absolute Count_FLAG', 'CD16/56%_FLAG', 'CD19_FLAG', 'CD19 %_FLAG', 'CD19 Absolute Count_FLAG', 'CD2_FLAG', 'CD20_FLAG', 'CD20 %_FLAG', 'CD20 Absolute Count_FLAG', 'CD23_FLAG', 'CD3 %_FLAG', 'CD3 Absolute Count_FLAG', 'CD3 Cells, Percent_FLAG', 'CD33_FLAG', 'CD34_FLAG', 'CD4 Cells, Percent_FLAG', 'CD4/CD8 Ratio_FLAG', 'CD45_FLAG', 'CD5_FLAG', 'CD5 %_FLAG', 'CD5 Absolute Count_FLAG', 'CD56_FLAG', 'CD64_FLAG', 'CD7_FLAG', 'CD8 Cells, Percent_FLAG', 'CK-MB Index_FLAG', 'Calcium, Total_FLAG', 'Calculated Bicarbonate, Whole Blood_FLAG', 'Calculated TBG_FLAG', 'Calculated Thyroxine (T4) Index_FLAG', 'Calculated Total CO2_FLAG', 'Cancer Antigen 27.29_FLAG', 'Carboxyhemoglobin_FLAG', 'Carcinoembyronic Antigen (CEA)_FLAG', 'Centromere_FLAG', 'Chloride_FLAG', 'Chloride, Whole Blood_FLAG', 'Cholesterol Ratio (Total/HDL)_FLAG', 'Cholesterol, HDL_FLAG', 'Cholesterol, LDL, Calculated_FLAG', 'Cholesterol, LDL, Measured_FLAG', 'Cholesterol, Total_FLAG', 'Collagen_FLAG', 'Cortisol_FLAG', 'Creatine Kinase (CK)_FLAG', 'Creatine Kinase, MB Isoenzyme_FLAG', 'Creatinine_FLAG', 'Creatinine, Whole Blood_FLAG', 'Cryoglobulin_FLAG', 'Cyclosporin_FLAG', 'Cytomegalovirus Viral Load_FLAG', 'D-Dimer_FLAG', 'DHEA-Sulfate_FLAG', 'Digoxin_FLAG', 'Double Stranded DNA_FLAG', 'EDTA Hold_FLAG', 'EE1_FLAG', 'EE2_FLAG', 'EE3_FLAG', 'EE5_FLAG', 'EE6_FLAG', 'EE7_FLAG', 'Echinocytes_FLAG', 'Elliptocytes_FLAG', 'Envelope Cells_FLAG', 'Eosinophil Count_FLAG', 'Eosinophils_FLAG', 'Epinepherine_FLAG', 'Estimated GFR (MDRD equation)_FLAG', 'Ethanol_FLAG', 'FMC-7_FLAG', 'Factor II_FLAG', 'Factor V_FLAG', 'Factor VII_FLAG', 'Factor VIII_FLAG', 'Factor X_FLAG', 'Ferritin_FLAG', 'Fibrin Degradation Products_FLAG', 'Fibrinogen, Functional_FLAG', 'Folate_FLAG', 'Fragmented Cells_FLAG', 'Free Calcium_FLAG', 'Free Kappa_FLAG', 'Free Kappa/Free Lambda Ratio_FLAG', 'Free Lambda_FLAG', 'G6PD, Qualitative_FLAG', 'Gamma Glutamyltransferase_FLAG', 'Gentamicin_FLAG', 'Globulin_FLAG', 'Glucose_FLAG', 'Granulocyte Count_FLAG', 'Gray Top Hold (plasma)_FLAG', 'Green Top Hold (plasma)_FLAG', 'H_FLAG', 'H/O Smear_FLAG', 'HIT-Ab Interpreted Result_FLAG', 'HIT-Ab Numerical Result_FLAG', 'HIV 1 Ab Confirmation_FLAG', 'HIV 1 Viral Load_FLAG', 'HIV 2 Ab Confirmation_FLAG', 'HIV Screen_FLAG', 'HLA-DR_FLAG', 'HPE1_FLAG', 'HPE2_FLAG', 'HPE3_FLAG', 'HPE4_FLAG', 'HPE5_FLAG', 'HPE6_FLAG', 'HPE7_FLAG', 'HPE8_FLAG', 'Haptoglobin_FLAG', 'Hematocrit_FLAG', 'Hematocrit, Calculated_FLAG', 'Hemoglobin_FLAG', 'Hemoglobin A2_FLAG', 'Hemoglobin C_FLAG', 'Hemoglobin F_FLAG', 'Hemogloblin A_FLAG', 'Hemogloblin S_FLAG', 'Heparin_FLAG', 'Heparin, LMW_FLAG', 'Hepatitis A Virus Antibody_FLAG', 'Hepatitis A Virus IgM Antibody_FLAG', 'Hepatitis B Core Antibody, IgM_FLAG', 'Hepatitis B Surface Antibody_FLAG', 'Hepatitis B Surface Antigen_FLAG', 'Hepatitis B Viral Load_FLAG', 'Hepatitis B Virus Core Antibody_FLAG', 'Hepatitis C Viral Load_FLAG', 'Hepatitis C Virus Antibody_FLAG', 'Homocysteine_FLAG', 'Howell-Jolly Bodies_FLAG', 'Human Chorionic Gonadotropin_FLAG', 'Hypochromia_FLAG', 'I_FLAG', 'INR(PT)_FLAG', 'Immature Granulocytes_FLAG', 'Immunofixation_FLAG', 'Immunoglobulin A_FLAG', 'Immunoglobulin G_FLAG', 'Immunoglobulin M_FLAG', 'Immunophenotyping_FLAG', 'Inhibitor Screen_FLAG', 'Inpatient Hematology/Oncology Smear_FLAG', 'Intubated_FLAG', 'Iron_FLAG', 'Iron Binding Capacity, Total_FLAG', 'Kappa_FLAG', 'L_FLAG', 'LUC_FLAG', 'Lactate_FLAG', 'Lactate Dehydrogenase (LD)_FLAG', 'Lambda_FLAG', 'Large Platelets_FLAG', 'Light Green Top Hold_FLAG', 'Lipase_FLAG', 'Lithium_FLAG', 'Lupus Anticoagulant_FLAG', 'Lymphocytes_FLAG', 'Lymphocytes, Percent_FLAG', 'MCH_FLAG', 'MCHC_FLAG', 'MCV_FLAG', 'MacroOvalocytes_FLAG', 'Macrocytes_FLAG', 'Magnesium_FLAG', 'Metamyelocytes_FLAG', 'Methemoglobin_FLAG', 'Methotrexate_FLAG', 'Microcytes_FLAG', 'Monocytes_FLAG', 'Myelocytes_FLAG', 'NTproBNP_FLAG', 'Neutrophils_FLAG', 'Nucleated Red Cells_FLAG', 'O2 Flow_FLAG', 'Osmolality, Measured_FLAG', 'Other Cells_FLAG', 'Ovalocytes_FLAG', 'Oxygen_FLAG', 'Oxygen Saturation_FLAG', 'PEEP_FLAG', 'PT_FLAG', 'PTT_FLAG', 'Pappenheimer Bodies_FLAG', 'Parathyroid Hormone_FLAG', 'Pencil Cells_FLAG', 'Phenobarbital_FLAG', 'Phenytoin_FLAG', 'Phenytoin, Free_FLAG', 'Phenytoin, Percent Free_FLAG', 'Phosphate_FLAG', 'Plasma Cells_FLAG', 'Platelet Clumps_FLAG', 'Platelet Count_FLAG', 'Platelet Smear_FLAG', 'Poikilocytosis_FLAG', 'Polychromasia_FLAG', 'Potassium_FLAG', 'Potassium, Whole Blood_FLAG', 'Problem Specimen_FLAG', 'Promyelocytes_FLAG', 'Prostate Specific Antigen_FLAG', 'Protein C, Antigen_FLAG', 'Protein C, Functional_FLAG', 'Protein Electrophoresis_FLAG', 'Protein S, Antigen_FLAG', 'Protein S, Functional_FLAG', 'Protein, Total_FLAG', 'Quantitative G6PD_FLAG', 'RBC Morphology_FLAG', 'RDW_FLAG', 'RDW-SD_FLAG', 'RFXLDLM_FLAG', 'Rapamycin_FLAG', 'Red Blood Cells_FLAG', 'Red Top Hold_FLAG', 'Required O2_FLAG', 'Reticulocyte Count, Absolute_FLAG', 'Reticulocyte Count, Automated_FLAG', 'Reticulocyte Count, Manual_FLAG', 'Rheumatoid Factor_FLAG', 'STX1_FLAG', 'STX2_FLAG', 'STX3_FLAG', 'STX4_FLAG', 'STX5_FLAG', 'STX6_FLAG', 'Salicylate_FLAG', 'Schistocytes_FLAG', 'Sedimentation Rate_FLAG', 'Serum Viscosity_FLAG', 'Sickle Cells_FLAG', 'Sodium_FLAG', 'Sodium, Whole Blood_FLAG', 'Specimen Type_FLAG', 'Spherocytes_FLAG', 'Target Cells_FLAG', 'Teardrop Cells_FLAG', 'Temperature_FLAG', 'Thrombin_FLAG', 'Thyroglobulin_FLAG', 'Thyroid Peroxidase Antibodies_FLAG', 'Thyroid Stimulating Hormone_FLAG', 'Thyroxine (T4)_FLAG', 'Thyroxine (T4), Free_FLAG', 'Tidal Volume_FLAG', 'Tissue Transglutaminase Ab, IgA_FLAG', 'Tobramycin_FLAG', 'Transferrin_FLAG', 'Tricyclic Antidepressant Screen_FLAG', 'Triglycerides_FLAG', 'Triiodothyronine (T3)_FLAG', 'Troponin T_FLAG', 'Uptake Ratio_FLAG', 'Urea Nitrogen_FLAG', 'Uric Acid_FLAG', 'Valproic Acid_FLAG', 'Vancomycin_FLAG', 'Ventilation Rate_FLAG', 'Ventilator_FLAG', 'Vitamin B12_FLAG', 'Voided Specimen_FLAG', 'Von Willebrand Factor Activity_FLAG', 'Von Willebrand Factor Antigen_FLAG', 'WBC Count_FLAG', 'White Blood Cells_FLAG', 'Young Cells_FLAG', 'eAG_FLAG', 'pCO2_FLAG', 'pH_FLAG', 'pO2_FLAG', 'tacroFK_FLAG', 'gender', 'age']

In [5]:
matching_df = pd.read_csv("/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/matching_report.csv")

In [6]:
len(mimic_patients_df)

2813

## Transform

In [7]:
# @title GROQ JUDGE
class BaseJudge(ABC):

    @abstractmethod
    def generate(self, system_prompt, user_prompt):
        pass

class GroqJudge(BaseJudge):

    def __init__(self, api_key, model="deepseek-r1-distill-llama-70b"):
        self.client = OpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1"
        )
        self.model = model

    def generate(self, system_prompt, user_prompt):
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],
            temperature=0
        )

        return response.choices[0].message.content

In [8]:
# @title Clinical Match Engine

class BatchClinicalMatch:
    def __init__(self, model):
        # genai.configure(api_key=userdata.get(api_key))
        # self.model = genai.GenerativeModel(version_genai)
        self.model = model

    def _process_batch(self, batch_df, inclusion, exclusion):
        # Transformamos o lote de pacientes em uma lista compacta de JSON
        # patients_list = batch_df.to_json(orient='records')

        # 1. Converte o lote para uma lista de dicionários
        raw_patients = batch_df.to_dict(orient='records')

        # 2. LIMPEZA DINÂMICA: Remove campos nulos/vazios de cada paciente
        compact_patients = []
        for p in raw_patients:
            # Mantém apenas o que não é nulo, não é NaN e não é string vazia
            clean_p = {k: v for k, v in p.items() if pd.notna(v) and str(v).strip() != "" and str(v).lower() != "nan"}
            compact_patients.append(clean_p)

        # 3. Transforma a lista limpa em string JSON
        patients_json_string = json.dumps(compact_patients)

        system_prompt = """
          You are a Senior Clinical Trial Coordinator and Data Auditor.
          Your task is to verify which patients are eligible to a clinical trial based on the eligibility criteria.

          Evaluate if the patient truly satisfies the criteria provided for the study.
          Identify if there are any logical gaps, missing data in patient profile, or incorrect inclusion/exclusion decisions.

          Respond ONLY with valid JSON.
            """

        prompt = f"""
        As a clinical trial coordinator, analyze this batch of patient records against the criteria.

        STUDY CRITERIA:
        Inclusion: {inclusion}
        Exclusion: {exclusion}

        PATIENTS LIST (JSON):
        {patients_json_string}

        For each patient, decide if they are ELIGIBLE.
        Consider synonyms (e.g., 'Synthetic Substitute' = 'Prosthesis').
        'No pregnant women' = Males OK, non-pregnant Females OK.

        RETURN ONLY A JSON LIST of eligible patients in this format:
        [
          {{"subject_id": 123, "reason": "Short reason"}},
          {{"subject_id": 456, "reason": "Short reason"}}
        ]
        If NO patients are eligible, return an empty list [].
        """
        try:
            response = self.model.generate(system_prompt, prompt)
            response = response.replace("```json", "").replace("```", "").strip()
            if "<think>" in response:
                response = response.split("</think>")[-1].strip()
            return json.loads(response)
        except Exception as e:
            print(f"Erro na API Groq: {e}")
            return []

    def run_inference(self, studies_df, patients_df, batch_size=50, report_file="matching_report.csv", log_file="audit_log.csv"):
        # --- LÓGICA DE CHECKPOINT ---
        processed_ncts = set()
        if os.path.exists(report_file):
            existing_report = pd.read_csv(report_file)
            processed_ncts = set(existing_report['nct_id'].unique())
            print(f"Retomando progresso: {len(processed_ncts)} estudos já processados.")

        for _, study in tqdm(studies_df.iterrows(), total=len(studies_df), desc="Estudos"):
            nct_id = study['nct_id']

            # Pula se já estiver no arquivo
            if nct_id in processed_ncts:
                continue

            study_eligible_ids = []
            audit_data = []

            for i in range(0, len(patients_df), batch_size):
                print(f" -> Processando lote {i//batch_size + 1} de {len(patients_df)//batch_size + 1}...", end="\r")
                batch = patients_df.iloc[i : i + batch_size]
                results = self._process_batch(batch, study['inclusion_criteria'], study['exclusion_criteria'])

                if results:
                    for res in results:
                        sid = res.get('subject_id')
                        study_eligible_ids.append(sid)
                        audit_data.append({
                            "nct_id": nct_id,
                            "subject_id": sid,
                            "reason": res.get('reason')
                        })

                time.sleep(4) # Respeitando a cota da API

            # --- SALVAMENTO INCREMENTAL ---
            # Salva o relatório principal
            report_row = pd.DataFrame([{
                "nct_id": nct_id,
                "eligible_count": len(study_eligible_ids),
                "subject_ids": json.dumps(study_eligible_ids)
            }])
            report_row.to_csv(report_file, mode='a', header=not os.path.exists(report_file), index=False)

            # Salva o log de auditoria
            if audit_data:
                pd.DataFrame(audit_data).to_csv(log_file, mode='a', header=not os.path.exists(log_file), index=False)

            # Adiciona aos processados para controle em tempo de execução
            processed_ncts.add(nct_id)

        return pd.read_csv(report_file), pd.read_csv(log_file)

In [9]:
## Main

In [10]:
# @title Define Engine
judge = GroqJudge(
        api_key=userdata.get("JudgeOpenRouter"),
        model="openai/gpt-oss-120b"
    )
engine = BatchClinicalMatch(
    # api_key="ParsingGeminiAPI",
    # version_genai = 'gemini-2.5-flash'
    model=judge
)

In [11]:
# @title Subsets data
all_cols = mimic_patients_df.columns.tolist()

cols_obrigatorias = ['subject_id', 'gender', 'age', 'name_diag_principal', 'list_procedures', 'HPI', 'chief_complaint']
to_ignore = ['hadm_id']
cols_com_dados = mimic_patients_df.columns[mimic_patients_df.notna().sum() > 0].tolist()
filtered_cols = [c for c in cols_com_dados if c not in to_ignore and not c.endswith('_FLAG')]
cols_finais = list(set(cols_obrigatorias + filtered_cols))
patients_subset = mimic_patients_df[cols_finais].copy()

def trim_clinical_text(text, limit=600):
    text = str(text)
    if len(text) <= limit:
        return text

    # Pega os primeiros 300 e os últimos 300 caracteres
    half = limit // 2
    return text[:half] + "\n[...] [TEXT CUT] [...]\n" + text[-half:]

# Aplica no seu DataFrame
patients_subset['HPI'] = patients_subset['HPI'].apply(trim_clinical_text)

In [24]:
nct_id_list = matching_df['nct_id'].unique().tolist()
len(nct_id_list)

10

,Factor VII,"Osmolality, Measured",Uric Acid,PT,Lipase,Carboxyhemoglobin,"Reticulocyte Count, Manual",pH,Gentamicin,Phenytoin,...,Triiodothyronine (T3),Quantitative G6PD,Cancer Antigen 27.29,Cortisol,Vitamin B12,"Calcium, Total","Cholesterol, HDL",CD5 %,MCV,icd_diag_principal
0,NaN,NaN,NaN,11.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.4,NaN,NaN,89.0,I5022
1,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9.4,43.0,NaN,84.0,I472
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.9,NaN,NaN,90.0,I2510
3,NaN,NaN,NaN,12.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.6,NaN,NaN,91.0,I2109
4,NaN,NaN,NaN,14.8,NaN,NaN,NaN,7.40,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.1,NaN,NaN,96.0,I2510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,NaN,NaN,NaN,17.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.4,NaN,NaN,84.0,I2119
484,NaN,NaN,NaN,10.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.5,52.0,NaN,NaN,I2510
485,NaN,NaN,NaN,28.9,NaN,NaN,NaN,7.42,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.9,NaN,NaN,93.0,I5033
486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.8,36.0,NaN,83.0,I214
487,NaN,NaN,NaN,10.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8.8,NaN,NaN,95.0,I309

In [25]:
# @title Run report
for nct_id in nct_id_list[1:]:
    df_patients_subset_filtered = matching_df.copy()
    df_patients_subset_filtered['subject_ids'] = df_patients_subset_filtered['subject_ids'].apply(ast.literal_eval)
    df_patients_subset_filtered = df_patients_subset_filtered[df_patients_subset_filtered['nct_id'] == nct_id].explode('subject_ids')
    df_patients_subset_filtered = df_patients_subset_filtered[['subject_ids']]
    df_patients_subset_filtered = df_patients_subset_filtered.rename(columns={'subject_ids': 'subject_id'})
    df_patients_subset_filtered = df_patients_subset_filtered.drop_duplicates()
    df_patients_subset_filtered = patients_subset.merge(df_patients_subset_filtered, on='subject_id', how='inner')

    print(f"Processando estudo: {nct_id}")
    study_df_to_process = clinical_trials_df[clinical_trials_df['nct_id'] == nct_id]
    report_df, audit_df = engine.run_inference(
        study_df_to_process,
        df_patients_subset_filtered,
        batch_size = 50,
        report_file="/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/matching_judge.csv",
        log_file="/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/audit_judge_log.csv"
    )

Processando estudo: NCT00236236
Retomando progresso: 1 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Erro na API Groq: 'NoneType' object has no attribute 'replace'

Estudos: 100%|██████████| 1/1 [03:51<00:00, 231.12s/it]

Processando estudo: NCT01550107
Retomando progresso: 2 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Estudos: 100%|██████████| 1/1 [01:33<00:00, 93.07s/it]

Processando estudo: NCT00356044
Retomando progresso: 3 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Estudos: 100%|██████████| 1/1 [03:48<00:00, 228.10s/it]

Processando estudo: NCT02805387
Retomando progresso: 4 estudos já processados.

Estudos: 100%|██████████| 1/1 [00:00<00:00, 95.09it/s]

Processando estudo: NCT01642784
Retomando progresso: 5 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Estudos: 100%|██████████| 1/1 [01:55<00:00, 115.89s/it]

Processando estudo: NCT01139307
Retomando progresso: 6 estudos já processados.

Estudos: 100%|██████████| 1/1 [00:00<00:00, 115.84it/s]

Processando estudo: NCT02367716
Retomando progresso: 7 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Estudos: 100%|██████████| 1/1 [03:29<00:00, 209.36s/it]

Processando estudo: NCT00176384
Retomando progresso: 8 estudos já processados.

Estudos: 100%|██████████| 1/1 [00:00<00:00, 94.32it/s]

Processando estudo: NCT01510652
Retomando progresso: 9 estudos já processados.

Estudos:   0%|          | 0/1 [00:00<?, ?it/s]

Estudos: 100%|██████████| 1/1 [04:31<00:00, 271.93s/it]

In [18]:
df_judge = pd.read_csv("/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/matching_judge.csv")
# df_judge = df_judge.head(0)
df_judge
# df_judge.to_csv("/content/drive/My Drive/Mestrado/Dissertação/mimic-iv-ext-cardiac-disease/processed/matching_judge.csv", index=False)

,nct_id,eligible_count,subject_ids
0,NCT03319472,16,"[10093609, 10194132, 10362783, 11079862, 11799..."